### ISSUE TITLE
Changelogs

### ISSUE THREAD

**Issue by pierrbt** [Encode42/minecrafts.date#1]
You could maybe add changelogs of each version

**Comment by encode42** [comment]
This seems out-of-scope for the project. My primary goal is to just display release dates/age instead of providing information about each release.

However, newer changelogs can be found on [Quilt's Proxy](https://quiltmc.org/mc-patchnotes/) or the Minecraft wiki. I *could* just add a link to the changelog, since these changelogs are typically massive.

**Comment by pierrbt** [comment]
Yes it was just an idea.

**Comment by encode42** [comment]
A good one! Did some thinking and decided to try and implement a link to an external changelog. It'll fill up some blank space and provide more information for the user.

**Comment by encode42** [comment]
Implemented in ac72e46aaed9f76bcca6e6ed885863650d0a7216

**Comment by pierrbt** [comment]
Cool !
